{% macro main(rule) %}
#>PeacockTV
DOMAIN,video-ads-module.ad-tech.nbcuni.com,{{rule}}

#>Tencent
#DOMAIN,btrace.qq.com,{{rule}}
#DOMAIN,mtrace.qq.com,{{rule}}
DOMAIN-KEYWORD,adstats,{{rule}}
DOMAIN,adstats.tencentmusic.com,{{rule}}

#>Viu
DOMAIN,r2---sn-j5o76n7e.gvt1.com,{{rule}}

#>WeTV
DOMAIN,btrace.wetvinfo.com,{{rule}}
DOMAIN,mtrace.wetvinfo.com,{{rule}}

#Advertising
DOMAIN-KEYWORD,adservice,{{rule}}

#Privacy
#>Google
DOMAIN,safebrowsing.googleapis.com,{{rule}}
#>Tencent
DOMAIN,safebrowsing.urlsec.qq.com,{{rule}}

#InternetServiceProvidersHijacking
DOMAIN-SUFFIX,17gouwuba.com,{{rule}}
DOMAIN-SUFFIX,186078.com,{{rule}}
DOMAIN-SUFFIX,189key.com,{{rule}}
DOMAIN-SUFFIX,189zj.cn,{{rule}}
DOMAIN-SUFFIX,285680.com,{{rule}}
DOMAIN-SUFFIX,3721zh.com,{{rule}}
DOMAIN-SUFFIX,4336wang.cn,{{rule}}
DOMAIN-SUFFIX,51chumoping.com,{{rule}}
DOMAIN-SUFFIX,51mld.cn,{{rule}}
DOMAIN-SUFFIX,51mypc.cn,{{rule}}
DOMAIN-SUFFIX,58mingri.cn,{{rule}}
DOMAIN-SUFFIX,58mingtian.cn,{{rule}}
DOMAIN-SUFFIX,5vl58stm.com,{{rule}}
DOMAIN-SUFFIX,6d63d3.com,{{rule}}
DOMAIN-SUFFIX,7gg.cc,{{rule}}
DOMAIN-SUFFIX,91veg.com,{{rule}}
DOMAIN-SUFFIX,9s6q.cn,{{rule}}
DOMAIN-SUFFIX,adsame.com,{{rule}}
DOMAIN-SUFFIX,akuai.top,{{rule}}
DOMAIN-SUFFIX,atplay.cn,{{rule}}
DOMAIN-SUFFIX,baiwanchuangyi.com,{{rule}}
DOMAIN-SUFFIX,beerto.cn,{{rule}}
DOMAIN-SUFFIX,beilamusi.com,{{rule}}
DOMAIN-SUFFIX,benshiw.net,{{rule}}
DOMAIN-SUFFIX,bianxianmao.com,{{rule}}
DOMAIN-SUFFIX,bkyhq.cn,{{rule}}
DOMAIN-SUFFIX,bryonypie.com,{{rule}}
DOMAIN-SUFFIX,cishantao.com,{{rule}}
DOMAIN-SUFFIX,cszlks.com,{{rule}}
DOMAIN-SUFFIX,cudaojia.com,{{rule}}
DOMAIN-SUFFIX,dafapromo.com,{{rule}}
DOMAIN-SUFFIX,daitdai.com,{{rule}}
DOMAIN-SUFFIX,dsaeerf.com,{{rule}}
DOMAIN-SUFFIX,dugesheying.com,{{rule}}
DOMAIN-SUFFIX,dv8c1t.cn,{{rule}}
DOMAIN-SUFFIX,echatu.com,{{rule}}
DOMAIN-SUFFIX,erdoscs.com,{{rule}}
DOMAIN-SUFFIX,fan-yong.com,{{rule}}
DOMAIN-SUFFIX,feih.com.cn,{{rule}}
DOMAIN-SUFFIX,fjlqqc.com,{{rule}}
DOMAIN-SUFFIX,fkku194.com,{{rule}}
DOMAIN-SUFFIX,freedrive.cn,{{rule}}
DOMAIN-SUFFIX,gclick.cn,{{rule}}
DOMAIN-SUFFIX,goufanli100.com,{{rule}}
DOMAIN-SUFFIX,goupaoerdai.com,{{rule}}
DOMAIN-SUFFIX,gouwubang.com,{{rule}}
DOMAIN-SUFFIX,gscxs.cn,{{rule}}
DOMAIN-SUFFIX,gzxnlk.com,{{rule}}
DOMAIN-SUFFIX,haoshengtoys.com,{{rule}}
DOMAIN-SUFFIX,hbssjd.cn,{{rule}}
DOMAIN-SUFFIX,hyunke.com,{{rule}}
DOMAIN-SUFFIX,ichaosheng.com,{{rule}}
DOMAIN-SUFFIX,ishop789.com,{{rule}}
DOMAIN-SUFFIX,jdkic.com,{{rule}}
DOMAIN-SUFFIX,jiubuhua.com,{{rule}}
DOMAIN-SUFFIX,jsncke.com,{{rule}}
DOMAIN-SUFFIX,junkucm.com,{{rule}}
DOMAIN-SUFFIX,jwg365.cn,{{rule}}
DOMAIN-SUFFIX,kawo77.com,{{rule}}
DOMAIN-SUFFIX,kualianyingxiao.cn,{{rule}}
DOMAIN-SUFFIX,kumihua.com,{{rule}}
DOMAIN-SUFFIX,ltheanine.cn,{{rule}}
DOMAIN-SUFFIX,lvehaisen.com,{{rule}}
DOMAIN-SUFFIX,maipinshangmao.com,{{rule}}
DOMAIN-SUFFIX,minisplat.cn,{{rule}}
DOMAIN-SUFFIX,mkitgfs.com,{{rule}}
DOMAIN-SUFFIX,mlnbike.com,{{rule}}
DOMAIN-SUFFIX,mobjump.com,{{rule}}
DOMAIN-SUFFIX,nbkbgd.cn,{{rule}}
DOMAIN-SUFFIX,newapi.com,{{rule}}
DOMAIN-SUFFIX,pinzhitmall.com,{{rule}}
DOMAIN-SUFFIX,poppyta.com,{{rule}}
DOMAIN-SUFFIX,qianchuanghr.com,{{rule}}
DOMAIN-SUFFIX,qichexin.com,{{rule}}
DOMAIN-SUFFIX,qinchugudao.com,{{rule}}
DOMAIN-SUFFIX,quanliyouxi.cn,{{rule}}
DOMAIN-SUFFIX,qutaobi.com,{{rule}}
DOMAIN-SUFFIX,ry51w.cn,{{rule}}
DOMAIN-SUFFIX,sg536.cn,{{rule}}
DOMAIN-SUFFIX,sifubo.cn,{{rule}}
DOMAIN-SUFFIX,sifuce.cn,{{rule}}
DOMAIN-SUFFIX,sifuda.cn,{{rule}}
DOMAIN-SUFFIX,sifufu.cn,{{rule}}
DOMAIN-SUFFIX,sifuge.cn,{{rule}}
DOMAIN-SUFFIX,sifugu.cn,{{rule}}
DOMAIN-SUFFIX,sifuhe.cn,{{rule}}
DOMAIN-SUFFIX,sifuhu.cn,{{rule}}
DOMAIN-SUFFIX,sifuji.cn,{{rule}}
DOMAIN-SUFFIX,sifuka.cn,{{rule}}
DOMAIN-SUFFIX,smgru.net,{{rule}}
DOMAIN-SUFFIX,taoggou.com,{{rule}}
DOMAIN-SUFFIX,tcxshop.com,{{rule}}
DOMAIN-SUFFIX,tjqonline.cn,{{rule}}
DOMAIN-SUFFIX,topitme.com,{{rule}}
DOMAIN-SUFFIX,tt114.net,{{rule}}
DOMAIN-SUFFIX,tt3sm4.cn,{{rule}}
DOMAIN-SUFFIX,tuia.cn,{{rule}}
DOMAIN-SUFFIX,tuipenguin.com,{{rule}}
DOMAIN-SUFFIX,tuitiger.com,{{rule}}
DOMAIN-SUFFIX,urlaw.cn,{{rule}}
DOMAIN-SUFFIX,urlet.cn,{{rule}}
DOMAIN-SUFFIX,websd8.com,{{rule}}
DOMAIN-SUFFIX,wsgblw.com,{{rule}}
DOMAIN-SUFFIX,wx16999.com,{{rule}}
DOMAIN-SUFFIX,xchmai.com,{{rule}}
DOMAIN-SUFFIX,xiaohuau.xyz,{{rule}}
DOMAIN-SUFFIX,ygyzx.cn,{{rule}}
DOMAIN-SUFFIX,yinmong.com,{{rule}}
DOMAIN-SUFFIX,yitaopt.com,{{rule}}
DOMAIN-SUFFIX,yjqiqi.com,{{rule}}
DOMAIN-SUFFIX,yukhj.com,{{rule}}
DOMAIN-SUFFIX,zhaozecheng.cn,{{rule}}
DOMAIN-SUFFIX,zhenxinet.com,{{rule}}
DOMAIN-SUFFIX,zlne800.com,{{rule}}
DOMAIN-SUFFIX,zmlled.cn,{{rule}}
DOMAIN-SUFFIX,zunmi.cn,{{rule}}
DOMAIN-SUFFIX,zzd6.com,{{rule}}
IP-CIDR,39.107.15.115/32,no-resolve,{{rule}}
IP-CIDR,47.89.59.182/32,no-resolve,{{rule}}
IP-CIDR,103.49.209.27/32,no-resolve,{{rule}}
IP-CIDR,123.56.152.96/32,no-resolve,{{rule}}
#>ChinaTelecom
IP-CIDR,61.160.200.223/32,no-resolve,{{rule}}
IP-CIDR,61.160.200.242/32,no-resolve,{{rule}}
IP-CIDR,61.160.200.252/32,no-resolve,{{rule}}
IP-CIDR,61.174.50.214/32,no-resolve,{{rule}}
IP-CIDR,111.175.220.163/32,no-resolve,{{rule}}
IP-CIDR,111.175.220.164/32,no-resolve,{{rule}}
IP-CIDR,122.229.8.47/32,no-resolve,{{rule}}
IP-CIDR,122.229.29.89/32,no-resolve,{{rule}}
IP-CIDR,124.232.160.178/32,no-resolve,{{rule}}
IP-CIDR,175.6.223.15/32,no-resolve,{{rule}}
IP-CIDR,183.59.53.237/32,no-resolve,{{rule}}
IP-CIDR,218.93.127.37/32,no-resolve,{{rule}}
IP-CIDR,221.228.17.152/32,no-resolve,{{rule}}
IP-CIDR,221.231.6.79/32,no-resolve,{{rule}}
IP-CIDR,222.186.61.91/32,no-resolve,{{rule}}
IP-CIDR,222.186.61.95/32,no-resolve,{{rule}}
IP-CIDR,222.186.61.96/32,no-resolve,{{rule}}
IP-CIDR,222.186.61.97/32,no-resolve,{{rule}}
#>ChinaUnicom
IP-CIDR,106.75.231.48/32,no-resolve,{{rule}}
IP-CIDR,119.4.249.166/32,no-resolve,{{rule}}
IP-CIDR,220.196.52.141/32,no-resolve,{{rule}}
IP-CIDR,221.6.4.148/32,no-resolve,{{rule}}
#>ChinaMobile
IP-CIDR,114.247.28.96/32,no-resolve,{{rule}}
IP-CIDR,120.240.95.37/32,no-resolve,{{rule}}
IP-CIDR,221.179.131.72/32,no-resolve,{{rule}}
IP-CIDR,221.179.140.145/32,no-resolve,{{rule}}
#>Dr.Peng
IP-CIDR,115.182.16.79/32,no-resolve,{{rule}}
IP-CIDR,118.144.88.126/32,no-resolve,{{rule}}
IP-CIDR,118.144.88.215/32,no-resolve,{{rule}}
IP-CIDR,118.144.88.216/32,no-resolve,{{rule}}
IP-CIDR,120.76.189.132/32,no-resolve,{{rule}}
IP-CIDR,124.14.21.147/32,no-resolve,{{rule}}
IP-CIDR,124.14.21.151/32,no-resolve,{{rule}}
IP-CIDR,180.166.52.24/32,no-resolve,{{rule}}
IP-CIDR,211.161.101.106/32,no-resolve,{{rule}}
IP-CIDR,211.161.101.110/32,no-resolve,{{rule}}
IP-CIDR,220.115.251.25/32,no-resolve,{{rule}}
IP-CIDR,222.73.156.235/32,no-resolve,{{rule}}

#Malware
#>HuaweiAspiegelBot
IP-CIDR,114.119.160.0/21,no-resolve,{{rule}}
#>KuaiZip
#https://zhuanlan.zhihu.com/p/39534279
DOMAIN-SUFFIX,kuaizip.com,{{rule}}
#>MacKeeper
#https://www.lizhi.io/blog/40002904
DOMAIN-SUFFIX,mackeeper.com,{{rule}}
DOMAIN-SUFFIX,zryydi.com,{{rule}}
#>AdobeFlashChinaSpecialEdition
#https://www.zhihu.com/question/281163698/answer/441388130
DOMAIN-SUFFIX,flash.cn,{{rule}}
DOMAIN,geo2.adobe.com,{{rule}}
#>C&JMarketing
#https://www.zhihu.com/question/46746200
DOMAIN-SUFFIX,4009997658.com,{{rule}}
DOMAIN-SUFFIX,abbyychina.com,{{rule}}
DOMAIN-SUFFIX,alienskins.cn,{{rule}}
DOMAIN-SUFFIX,anydeskchina.cn,{{rule}}
DOMAIN-SUFFIX,bartender.cc,{{rule}}
DOMAIN-SUFFIX,betterzip.net,{{rule}}
DOMAIN-SUFFIX,betterzipcn.com,{{rule}}
DOMAIN-SUFFIX,beyondcompare.cc,{{rule}}
DOMAIN-SUFFIX,bingdianhuanyuan.cn,{{rule}}
DOMAIN-SUFFIX,chemdraw.com.cn,{{rule}}
DOMAIN-SUFFIX,cjmakeding.com,{{rule}}
DOMAIN-SUFFIX,cjmkt.com,{{rule}}
DOMAIN-SUFFIX,codesoftchina.com,{{rule}}
DOMAIN-SUFFIX,coreldrawchina.com,{{rule}}
DOMAIN-SUFFIX,crossoverchina.com,{{rule}}
DOMAIN-SUFFIX,dongmansoft.com,{{rule}}
DOMAIN-SUFFIX,earmasterchina.cn,{{rule}}
DOMAIN-SUFFIX,easyrecoverychina.com,{{rule}}
DOMAIN-SUFFIX,ediuschina.com,{{rule}}
DOMAIN-SUFFIX,flstudiochina.com,{{rule}}
DOMAIN-SUFFIX,folxchina.cn,{{rule}}
DOMAIN-SUFFIX,formysql.com,{{rule}}
DOMAIN-SUFFIX,guitarpro.cc,{{rule}}
DOMAIN-SUFFIX,huishenghuiying.com.cn,{{rule}}
DOMAIN-SUFFIX,hypeapp.cn,{{rule}}
DOMAIN-SUFFIX,hypersnap.net,{{rule}}
DOMAIN-SUFFIX,iconworkshop.cn,{{rule}}
DOMAIN-SUFFIX,idmchina.net,{{rule}}
DOMAIN-SUFFIX,imazingchina.com,{{rule}}
DOMAIN-SUFFIX,imindmap.cc,{{rule}}
DOMAIN-SUFFIX,jihehuaban.com.cn,{{rule}}
DOMAIN-SUFFIX,keyshot.cc,{{rule}}
DOMAIN-SUFFIX,kingdeecn.cn,{{rule}}
DOMAIN-SUFFIX,logoshejishi.com,{{rule}}
DOMAIN-SUFFIX,luping.net.cn,{{rule}}
DOMAIN-SUFFIX,mairuan.cn,{{rule}}
DOMAIN-SUFFIX,mairuan.com,{{rule}}
DOMAIN-SUFFIX,mairuan.com.cn,{{rule}}
DOMAIN-SUFFIX,mairuan.net,{{rule}}
DOMAIN-SUFFIX,mairuanwang.com,{{rule}}
DOMAIN-SUFFIX,makeding.com,{{rule}}
DOMAIN-SUFFIX,mathtype.cn,{{rule}}
DOMAIN-SUFFIX,mindmanager.cc,{{rule}}
DOMAIN-SUFFIX,mindmanager.cn,{{rule}}
DOMAIN-SUFFIX,mindmapper.cc,{{rule}}
DOMAIN-SUFFIX,mycleanmymac.com,{{rule}}
DOMAIN-SUFFIX,nicelabel.cc,{{rule}}
DOMAIN-SUFFIX,ntfsformac.cc,{{rule}}
DOMAIN-SUFFIX,ntfsformac.cn,{{rule}}
DOMAIN-SUFFIX,overturechina.com,{{rule}}
DOMAIN-SUFFIX,passwordrecovery.cn,{{rule}}
DOMAIN-SUFFIX,pdfexpert.cc,{{rule}}
DOMAIN-SUFFIX,photozoomchina.com,{{rule}}
DOMAIN-SUFFIX,shankejingling.com,{{rule}}
DOMAIN-SUFFIX,ultraiso.net,{{rule}}
DOMAIN-SUFFIX,vegaschina.cn,{{rule}}
DOMAIN-SUFFIX,xitongqingli.com,{{rule}}
DOMAIN-SUFFIX,xmindchina.net,{{rule}}
DOMAIN-SUFFIX,xshellcn.com,{{rule}}
DOMAIN-SUFFIX,yihuifu.cn,{{rule}}
DOMAIN-SUFFIX,yuanchengxiezuo.com,{{rule}}
DOMAIN-SUFFIX,zbrushcn.com,{{rule}}
DOMAIN-SUFFIX,zhzzx.com,{{rule}}
{% endmacro %}