{% macro main(rule) %}
#(DNSCachePollution)

# > 自定义代理
DOMAIN,story.st8.one,DIRECT
DOMAIN-SUFFIX,txrjy.com,{{rule}}

# > Amazon
DOMAIN-SUFFIX,amazon.co.jp,{{rule}}
DOMAIN,d3c33hcgiwev3.cloudfront.net,{{rule}}
DOMAIN,payments-jp.amazon.com,{{rule}}
DOMAIN,s3-ap-northeast-1.amazonaws.com,{{rule}}
DOMAIN,s3-ap-southeast-2.amazonaws.com,{{rule}}
# > Akamai
DOMAIN,a248.e.akamai.net,{{rule}}
DOMAIN,a771.dscq.akamai.net,{{rule}}
# > Apple
DOMAIN,testflight.apple.com,{{rule}}
# > Crypto
DOMAIN-SUFFIX,aex.com,{{rule}}
DOMAIN-SUFFIX,bibox.com,{{rule}}
DOMAIN-SUFFIX,binance.cc,{{rule}}
DOMAIN-SUFFIX,binance.com,{{rule}}
DOMAIN-SUFFIX,binance.us,{{rule}}
DOMAIN-SUFFIX,bitcointalk.org,{{rule}}
DOMAIN-SUFFIX,bitfinex.com,{{rule}}
DOMAIN-SUFFIX,bithumb.com,{{rule}}
DOMAIN-SUFFIX,bitmex.com,{{rule}}
DOMAIN-SUFFIX,bitstamp.net,{{rule}}
DOMAIN-SUFFIX,bittrex.com,{{rule}}
DOMAIN-SUFFIX,bybit.com,{{rule}}
DOMAIN-SUFFIX,coinbase.com,{{rule}}
DOMAIN-SUFFIX,coincheck.com,{{rule}}
DOMAIN-SUFFIX,coingecko.com,{{rule}}
DOMAIN-SUFFIX,coinmarketcap.com,{{rule}}
DOMAIN-SUFFIX,coinone.co.kr,{{rule}}
DOMAIN-SUFFIX,ftx.com,{{rule}}
DOMAIN-SUFFIX,gate.io,{{rule}}
DOMAIN-SUFFIX,gemini.com,{{rule}}
DOMAIN-SUFFIX,huobi.com,{{rule}}
DOMAIN-SUFFIX,korbit.co.kr,{{rule}}
DOMAIN-SUFFIX,kraken.com,{{rule}}
DOMAIN-SUFFIX,kucoin.com,{{rule}}
DOMAIN-SUFFIX,liquid.com,{{rule}}
DOMAIN-SUFFIX,okex.com,{{rule}}
DOMAIN-SUFFIX,poloniex.com,{{rule}}
DOMAIN-SUFFIX,uniswap.org,{{rule}}
DOMAIN-SUFFIX,zb.com,{{rule}}
# > Discord
DOMAIN-SUFFIX,discord.com,{{rule}}
DOMAIN-SUFFIX,discordapp.com,{{rule}}
DOMAIN-SUFFIX,discordapp.net,{{rule}}
# > Dropbox
DOMAIN-SUFFIX,dropbox.com,{{rule}}
DOMAIN-SUFFIX,dropboxapi.com,{{rule}}
DOMAIN-SUFFIX,dropboxusercontent.com,{{rule}}
# > Facebook
DOMAIN-SUFFIX,cdninstagram.com,{{rule}}
DOMAIN-SUFFIX,facebook.com,{{rule}}
DOMAIN-SUFFIX,facebook.net,{{rule}}
DOMAIN-SUFFIX,fb.com,{{rule}}
DOMAIN-SUFFIX,fb.me,{{rule}}
DOMAIN-SUFFIX,fbaddins.com,{{rule}}
DOMAIN-SUFFIX,fbcdn.net,{{rule}}
DOMAIN-SUFFIX,fbsbx.com,{{rule}}
DOMAIN-SUFFIX,fbworkmail.com,{{rule}}
DOMAIN-SUFFIX,instagram.com,{{rule}}
DOMAIN-SUFFIX,m.me,{{rule}}
DOMAIN-SUFFIX,messenger.com,{{rule}}
DOMAIN-SUFFIX,oculus.com,{{rule}}
DOMAIN-SUFFIX,oculuscdn.com,{{rule}}
DOMAIN-SUFFIX,rocksdb.org,{{rule}}
DOMAIN-SUFFIX,whatsapp.com,{{rule}}
DOMAIN-SUFFIX,whatsapp.net,{{rule}}
# > Github
DOMAIN-SUFFIX,github.com,{{rule}}
DOMAIN-SUFFIX,github.io,{{rule}}
DOMAIN-SUFFIX,githubusercontent.com,{{rule}}
# > Google
DOMAIN-KEYWORD,gmail,{{rule}}
DOMAIN-KEYWORD,google,{{rule}}
DOMAIN-SUFFIX,1e100.net,{{rule}}
DOMAIN-SUFFIX,2mdn.net,{{rule}}
DOMAIN-SUFFIX,app-measurement.net,{{rule}}
DOMAIN-SUFFIX,g.co,{{rule}}
DOMAIN-SUFFIX,ggpht.com,{{rule}}
DOMAIN-SUFFIX,goo.gl,{{rule}}
DOMAIN-SUFFIX,googleapis.cn,DIRECT
DOMAIN-SUFFIX,googleapis.com,{{rule}}
DOMAIN-SUFFIX,connectivitycheck.gstatic.com,DIRECT
DOMAIN-SUFFIX,gstatic.cn,{{rule}}
DOMAIN-SUFFIX,gstatic.com,{{rule}}
DOMAIN-SUFFIX,gvt0.com,{{rule}}
DOMAIN-SUFFIX,gvt1.com,{{rule}}
DOMAIN-SUFFIX,gvt2.com,{{rule}}
DOMAIN-SUFFIX,gvt3.com,{{rule}}
# DOMAIN-SUFFIX,xn--ngstr-lra8j.com,{{rule}}
DOMAIN-SUFFIX,youtu.be,{{rule}}
DOMAIN-SUFFIX,youtube-nocookie.com,{{rule}}
DOMAIN-SUFFIX,youtube.com,{{rule}}
DOMAIN-SUFFIX,yt.be,{{rule}}
DOMAIN-SUFFIX,ytimg.com,{{rule}}
IP-CIDR,74.125.0.0/16,{{rule}},no-resolve
IP-CIDR,173.194.0.0/16,{{rule}},no-resolve

# > Line
DOMAIN-SUFFIX,line.me,{{rule}}
DOMAIN-SUFFIX,line-apps.com,{{rule}}
DOMAIN-SUFFIX,line-scdn.net,{{rule}}
DOMAIN-SUFFIX,naver.jp,{{rule}}
IP-CIDR,103.2.30.0/23,{{rule}}
IP-CIDR,125.209.208.0/20,{{rule}},no-resolve
IP-CIDR,147.92.128.0/17,{{rule}},no-resolve
IP-CIDR,203.104.144.0/21,{{rule}},no-resolve
# > Microsoft
DOMAIN-SUFFIX,aka.ms,{{rule}}
DOMAIN-SUFFIX,onedrive.live.com,{{rule}}
DOMAIN-SUFFIX,streaming.mediaservices.windows.net,{{rule}}
DOMAIN,assets1.xboxlive.com,{{rule}}
DOMAIN,assets2.xboxlive.com,{{rule}}
DOMAIN,az416426.vo.msecnd.net,{{rule}}
DOMAIN,az668014.vo.msecnd.net,{{rule}}
# > TheNewYorkTimes
DOMAIN-SUFFIX,nyt.com,{{rule}}
DOMAIN-SUFFIX,nytchina.com,{{rule}}
DOMAIN-SUFFIX,nytcn.me,{{rule}}
DOMAIN-SUFFIX,nytco.com,{{rule}}
DOMAIN-SUFFIX,nytimes.com,{{rule}}
DOMAIN-SUFFIX,nytimg.com,{{rule}}
DOMAIN-SUFFIX,nytlog.com,{{rule}}
DOMAIN-SUFFIX,nytstyle.com,{{rule}}
# > Pinterest
DOMAIN-SUFFIX,pinterest.at,{{rule}}
DOMAIN-SUFFIX,pinterest.ca,{{rule}}
DOMAIN-SUFFIX,pinterest.co.uk,{{rule}}
DOMAIN-SUFFIX,pinterest.com,{{rule}}
DOMAIN-SUFFIX,pinterest.de,{{rule}}
DOMAIN-SUFFIX,pinterest.fr,{{rule}}
DOMAIN-SUFFIX,pinterest.jp,{{rule}}
DOMAIN-SUFFIX,pinterest.se,{{rule}}
# > pixiv
DOMAIN-SUFFIX,pixiv.net,{{rule}}
DOMAIN-SUFFIX,pixiv.org,{{rule}}
DOMAIN-SUFFIX,pximg.net,{{rule}}
# > Reddit,{{rule}}
DOMAIN-SUFFIX,redd.it,{{rule}}
DOMAIN-SUFFIX,reddit.com,{{rule}}
DOMAIN-SUFFIX,redditmedia.com,{{rule}}

# > Twitter
DOMAIN-SUFFIX,pscp.tv,{{rule}}
DOMAIN-SUFFIX,periscope.tv,{{rule}}
DOMAIN-SUFFIX,t.co,{{rule}}
DOMAIN-SUFFIX,twimg.co,{{rule}}
DOMAIN-SUFFIX,twimg.com,{{rule}}
DOMAIN-SUFFIX,twitpic.com,{{rule}}
DOMAIN-SUFFIX,twitter.com,{{rule}}
DOMAIN-SUFFIX,vine.co,{{rule}}
# > WikimediaFoundation
DOMAIN-SUFFIX,wikileaks.org,{{rule}}
DOMAIN-SUFFIX,wikimapia.org,{{rule}}
DOMAIN-SUFFIX,wikimedia.org,{{rule}}
DOMAIN-SUFFIX,wikinews.org,{{rule}}
DOMAIN-SUFFIX,wikipedia.org,{{rule}}
DOMAIN-SUFFIX,wikiquote.org,{{rule}}
# > Others
DOMAIN-SUFFIX,4shared.com,{{rule}}
DOMAIN-SUFFIX,9cache.com,{{rule}}
DOMAIN-SUFFIX,9gag.com,{{rule}}
DOMAIN-SUFFIX,abc.com,{{rule}}
DOMAIN-SUFFIX,abc.net.au,{{rule}}
DOMAIN-SUFFIX,abebooks.com,{{rule}}
DOMAIN-SUFFIX,ao3.org,{{rule}}
DOMAIN-SUFFIX,apigee.com,{{rule}}
DOMAIN-SUFFIX,apkcombo.com,{{rule}}
DOMAIN-SUFFIX,apk-dl.com,{{rule}}
DOMAIN-SUFFIX,apkfind.com,{{rule}}
DOMAIN-SUFFIX,apkmirror.com,{{rule}}
DOMAIN-SUFFIX,apkmonk.com,{{rule}}
DOMAIN-SUFFIX,apkpure.com,{{rule}}
DOMAIN-SUFFIX,aptoide.com,{{rule}}
DOMAIN-SUFFIX,archive.is,{{rule}}
DOMAIN-SUFFIX,archive.org,{{rule}}
DOMAIN-SUFFIX,archiveofourown.com,{{rule}}
DOMAIN-SUFFIX,archiveofourown.org,{{rule}}
DOMAIN-SUFFIX,arte.tv,{{rule}}
DOMAIN-SUFFIX,artstation.com,{{rule}}
DOMAIN-SUFFIX,arukas.io,{{rule}}
DOMAIN-SUFFIX,ask.com,{{rule}}
DOMAIN-SUFFIX,avg.com,{{rule}}
DOMAIN-SUFFIX,avgle.com,{{rule}}
DOMAIN-SUFFIX,badoo.com,{{rule}}
DOMAIN-SUFFIX,bandcamp.com,{{rule}}
DOMAIN-SUFFIX,bandwagonhost.com,{{rule}}
DOMAIN-SUFFIX,bangkokpost.com,{{rule}}
DOMAIN-SUFFIX,bbc.com,{{rule}}
DOMAIN-SUFFIX,behance.net,{{rule}}
DOMAIN-SUFFIX,biggo.com.tw,{{rule}}
DOMAIN-SUFFIX,bit.ly,{{rule}}
DOMAIN-SUFFIX,bloglovin.com,{{rule}}
DOMAIN-SUFFIX,bloomberg.cn,{{rule}}
DOMAIN-SUFFIX,bloomberg.com,{{rule}}
DOMAIN-SUFFIX,blubrry.com,{{rule}}
DOMAIN-SUFFIX,book.com.tw,{{rule}}
DOMAIN-SUFFIX,booklive.jp,{{rule}}
DOMAIN-SUFFIX,books.com.tw,{{rule}}
DOMAIN-SUFFIX,boslife.net,{{rule}}
DOMAIN-SUFFIX,box.com,{{rule}}
DOMAIN-SUFFIX,brave.com,{{rule}}
DOMAIN-SUFFIX,businessinsider.com,{{rule}}
DOMAIN-SUFFIX,buzzfeed.com,{{rule}}
DOMAIN-SUFFIX,bwh1.net,{{rule}}
DOMAIN-SUFFIX,castbox.fm,{{rule}}
DOMAIN-SUFFIX,cbc.ca,{{rule}}
DOMAIN-SUFFIX,cdw.com,{{rule}}
DOMAIN-SUFFIX,change.org,{{rule}}
DOMAIN-SUFFIX,channelnewsasia.com,{{rule}}
DOMAIN-SUFFIX,ck101.com,{{rule}}
DOMAIN-SUFFIX,clarionproject.org,{{rule}}
DOMAIN-SUFFIX,cloudcone.com,{{rule}}
DOMAIN-SUFFIX,clubhouseapi.com,{{rule}}
DOMAIN-SUFFIX,clyp.it,{{rule}}
DOMAIN-SUFFIX,cna.com.tw,{{rule}}
DOMAIN-SUFFIX,comparitech.com,{{rule}}
DOMAIN-SUFFIX,conoha.jp,{{rule}}
DOMAIN-SUFFIX,crucial.com,{{rule}}
DOMAIN-SUFFIX,cts.com.tw,{{rule}}
DOMAIN-SUFFIX,cw.com.tw,{{rule}}
DOMAIN-SUFFIX,cyberctm.com,{{rule}}
DOMAIN-SUFFIX,cyclingnews.com,{{rule}}
DOMAIN-SUFFIX,dailymotion.com,{{rule}}
DOMAIN-SUFFIX,dailyview.tw,{{rule}}
DOMAIN-SUFFIX,dandanzan.com,{{rule}}
DOMAIN-SUFFIX,daum.net,{{rule}}
DOMAIN-SUFFIX,daumcdn.net,{{rule}}
DOMAIN-SUFFIX,dcard.tw,{{rule}}
DOMAIN-SUFFIX,deadline.com,{{rule}}
DOMAIN-SUFFIX,deepdiscount.com,{{rule}}
DOMAIN-SUFFIX,depositphotos.com,{{rule}}
DOMAIN-SUFFIX,deviantart.com,{{rule}}
DOMAIN-SUFFIX,disconnect.me,{{rule}}
DOMAIN-SUFFIX,disqus.com,{{rule}}
DOMAIN-SUFFIX,dlercloud.com,{{rule}}
DOMAIN-SUFFIX,dmhy.org,{{rule}}
DOMAIN-SUFFIX,dns2go.com,{{rule}}
DOMAIN-SUFFIX,dowjones.com,{{rule}}
DOMAIN-SUFFIX,duckduckgo.com,{{rule}}
DOMAIN-SUFFIX,duyaoss.com,{{rule}}
DOMAIN-SUFFIX,dw.com,{{rule}}
DOMAIN-SUFFIX,dynu.com,{{rule}}
DOMAIN-SUFFIX,earthcam.com,{{rule}}
DOMAIN-SUFFIX,ebookservice.tw,{{rule}}
DOMAIN-SUFFIX,economist.com,{{rule}}
DOMAIN-SUFFIX,edgecastcdn.net,{{rule}}
DOMAIN-SUFFIX,edx-cdn.org,{{rule}}
DOMAIN-SUFFIX,elpais.com,{{rule}}
DOMAIN-SUFFIX,enanyang.my,{{rule}}
DOMAIN-SUFFIX,encyclopedia.com,{{rule}}
DOMAIN-SUFFIX,esoir.be,{{rule}}
DOMAIN-SUFFIX,etherscan.io,{{rule}}
DOMAIN-SUFFIX,euronews.com,{{rule}}
DOMAIN-SUFFIX,evozi.com,{{rule}}
DOMAIN-SUFFIX,exblog.jp,{{rule}}
DOMAIN-SUFFIX,feeder.co,{{rule}}
DOMAIN-SUFFIX,feedly.com,{{rule}}
DOMAIN-SUFFIX,feedx.net,{{rule}}
DOMAIN-SUFFIX,firech.at,{{rule}}
DOMAIN-SUFFIX,flickr.com,{{rule}}
DOMAIN-SUFFIX,flipboard.com,{{rule}}
DOMAIN-SUFFIX,flitto.com,{{rule}}
DOMAIN-SUFFIX,foreignpolicy.com,{{rule}}
DOMAIN-SUFFIX,fortawesome.com,{{rule}}
DOMAIN-SUFFIX,freetls.fastly.net,{{rule}}
DOMAIN-SUFFIX,friday.tw,{{rule}}
DOMAIN-SUFFIX,ft.com,{{rule}}
DOMAIN-SUFFIX,ftchinese.com,{{rule}}
DOMAIN-SUFFIX,ftimg.net,{{rule}}
DOMAIN-SUFFIX,genius.com,{{rule}}
DOMAIN-SUFFIX,getlantern.org,{{rule}}
DOMAIN-SUFFIX,getsync.com,{{rule}}
DOMAIN-SUFFIX,globalvoices.org,{{rule}}
DOMAIN-SUFFIX,goo.ne.jp,{{rule}}
DOMAIN-SUFFIX,goodreads.com,{{rule}}
DOMAIN-SUFFIX,gov.tw,{{rule}}
DOMAIN-SUFFIX,gravatar.com,{{rule}}
DOMAIN-SUFFIX,greatfire.org,{{rule}}
DOMAIN-SUFFIX,gumroad.com,{{rule}}
DOMAIN-SUFFIX,heroku.com,{{rule}}
DOMAIN-SUFFIX,hightail.com,{{rule}}
DOMAIN-SUFFIX,hk01.com,{{rule}}
DOMAIN-SUFFIX,hkbf.org,{{rule}}
DOMAIN-SUFFIX,hkbookcity.com,{{rule}}
DOMAIN-SUFFIX,hkej.com,{{rule}}
DOMAIN-SUFFIX,hket.com,{{rule}}
DOMAIN-SUFFIX,hootsuite.com,{{rule}}
DOMAIN-SUFFIX,hudson.org,{{rule}}
DOMAIN-SUFFIX,huffpost.com,{{rule}}
DOMAIN-SUFFIX,hyread.com.tw,{{rule}}
DOMAIN-SUFFIX,ibtimes.com,{{rule}}
DOMAIN-SUFFIX,i-cable.com,{{rule}}
DOMAIN-SUFFIX,icij.org,{{rule}}
DOMAIN-SUFFIX,icoco.com,{{rule}}
DOMAIN-SUFFIX,imgur.com,{{rule}}
DOMAIN-SUFFIX,independent.co.uk,{{rule}}
DOMAIN-SUFFIX,initiummall.com,{{rule}}
DOMAIN-SUFFIX,inoreader.com,{{rule}}
DOMAIN-SUFFIX,insecam.org,{{rule}}
DOMAIN-SUFFIX,ipfs.io,{{rule}}
DOMAIN-SUFFIX,issuu.com,{{rule}}
DOMAIN-SUFFIX,istockphoto.com,{{rule}}
DOMAIN-SUFFIX,japantimes.co.jp,{{rule}}
DOMAIN-SUFFIX,jiji.com,{{rule}}
DOMAIN-SUFFIX,jinx.com,{{rule}}
DOMAIN-SUFFIX,jkforum.net,{{rule}}
DOMAIN-SUFFIX,joinclubhouse.com,{{rule}}
DOMAIN-SUFFIX,joinmastodon.org,{{rule}}
DOMAIN-SUFFIX,justmysocks.net,{{rule}}
DOMAIN-SUFFIX,justpaste.it,{{rule}}
DOMAIN-SUFFIX,kadokawa.co.jp,{{rule}}
DOMAIN-SUFFIX,kakao.com,{{rule}}
DOMAIN-SUFFIX,kakaocorp.com,{{rule}}
DOMAIN-SUFFIX,kik.com,{{rule}}
DOMAIN-SUFFIX,kingkong.com.tw,{{rule}}
DOMAIN-SUFFIX,knowyourmeme.com,{{rule}}
DOMAIN-SUFFIX,kobo.com,{{rule}}
DOMAIN-SUFFIX,kobobooks.com,{{rule}}
DOMAIN-SUFFIX,kodingen.com,{{rule}}
DOMAIN-SUFFIX,lemonde.fr,{{rule}}
DOMAIN-SUFFIX,lepoint.fr,{{rule}}
DOMAIN-SUFFIX,lihkg.com,{{rule}}
DOMAIN-SUFFIX,limbopro.xyz,{{rule}}
DOMAIN-SUFFIX,listennotes.com,{{rule}}
DOMAIN-SUFFIX,livestream.com,{{rule}}
DOMAIN-SUFFIX,logimg.jp,{{rule}}
DOMAIN-SUFFIX,logmein.com,{{rule}}
DOMAIN-SUFFIX,mail.ru,{{rule}}
DOMAIN-SUFFIX,mailchimp.com,{{rule}}
DOMAIN-SUFFIX,marc.info,{{rule}}
DOMAIN-SUFFIX,matters.news,{{rule}}
DOMAIN-SUFFIX,maying.co,{{rule}}
DOMAIN-SUFFIX,medium.com,{{rule}}
DOMAIN-SUFFIX,mega.nz,{{rule}}
DOMAIN-SUFFIX,mergersandinquisitions.com,{{rule}}
DOMAIN-SUFFIX,mingpao.com,{{rule}}
DOMAIN-SUFFIX,mixi.jp,{{rule}}
DOMAIN-SUFFIX,mixlr.com,{{rule}}
DOMAIN-SUFFIX,mobile01.com,{{rule}}
DOMAIN-SUFFIX,mubi.com,{{rule}}
DOMAIN-SUFFIX,myspace.com,{{rule}}
DOMAIN-SUFFIX,myspacecdn.com,{{rule}}
DOMAIN-SUFFIX,nanyang.com,{{rule}}
DOMAIN-SUFFIX,nationalinterest.org,{{rule}}
DOMAIN-SUFFIX,naver.com,{{rule}}
DOMAIN-SUFFIX,nbcnews.com,{{rule}}
DOMAIN-SUFFIX,ndr.de,{{rule}}
DOMAIN-SUFFIX,neowin.net,{{rule}}
DOMAIN-SUFFIX,newstapa.org,{{rule}}
DOMAIN-SUFFIX,nexitally.com,{{rule}}
DOMAIN-SUFFIX,nhk.or.jp,{{rule}}
DOMAIN-SUFFIX,nii.ac.jp,{{rule}}
DOMAIN-SUFFIX,nikkei.com,{{rule}}
DOMAIN-SUFFIX,nitter.net,{{rule}}
DOMAIN-SUFFIX,nofile.io,{{rule}}
DOMAIN-SUFFIX,notion.so,{{rule}}
DOMAIN-SUFFIX,now.com,{{rule}}
DOMAIN-SUFFIX,nrk.no,{{rule}}
DOMAIN-SUFFIX,nuget.org,{{rule}}
DOMAIN-SUFFIX,nyaa.si,{{rule}}
DOMAIN-SUFFIX,ok.ru,{{rule}}
DOMAIN-SUFFIX,on.cc,{{rule}}
DOMAIN-SUFFIX,orientaldaily.com.my,{{rule}}
DOMAIN-SUFFIX,overcast.fm,{{rule}}
DOMAIN-SUFFIX,paltalk.com,{{rule}}
DOMAIN-SUFFIX,parsevideo.com,{{rule}}
DOMAIN-SUFFIX,pawoo.net,{{rule}}
DOMAIN-SUFFIX,pbxes.com,{{rule}}
DOMAIN-SUFFIX,pcdvd.com.tw,{{rule}}
DOMAIN-SUFFIX,pchome.com.tw,{{rule}}
DOMAIN-SUFFIX,pcloud.com,{{rule}}
DOMAIN-SUFFIX,peing.net,{{rule}}
DOMAIN-SUFFIX,picacomic.com,{{rule}}
DOMAIN-SUFFIX,pinimg.com,{{rule}}
DOMAIN-SUFFIX,player.fm,{{rule}}
DOMAIN-SUFFIX,plurk.com,{{rule}}
DOMAIN-SUFFIX,po18.tw,{{rule}}
DOMAIN-SUFFIX,potato.im,{{rule}}
DOMAIN-SUFFIX,potatso.com,{{rule}}
DOMAIN-SUFFIX,prism-break.org,{{rule}}
DOMAIN-SUFFIX,proxifier.com,{{rule}}
DOMAIN-SUFFIX,pt.im,{{rule}}
DOMAIN-SUFFIX,pts.org.tw,{{rule}}
DOMAIN-SUFFIX,pubu.com.tw,{{rule}}
DOMAIN-SUFFIX,pubu.tw,{{rule}}
DOMAIN-SUFFIX,pureapk.com,{{rule}}
DOMAIN-SUFFIX,quora.com,{{rule}}
DOMAIN-SUFFIX,quoracdn.net,{{rule}}
DOMAIN-SUFFIX,qz.com,{{rule}}
DOMAIN-SUFFIX,radio.garden,{{rule}}
DOMAIN-SUFFIX,rakuten.co.jp,{{rule}}
DOMAIN-SUFFIX,rarbgprx.org,{{rule}}
DOMAIN-SUFFIX,reabble.com,{{rule}}
DOMAIN-SUFFIX,readingtimes.com.tw,{{rule}}
DOMAIN-SUFFIX,readmoo.com,{{rule}}
DOMAIN-SUFFIX,redbubble.com,{{rule}}
DOMAIN-SUFFIX,resilio.com,{{rule}}
DOMAIN-SUFFIX,reuters.com,{{rule}}
DOMAIN-SUFFIX,reutersmedia.net,{{rule}}
DOMAIN-SUFFIX,rfi.fr,{{rule}}
DOMAIN-SUFFIX,roadshow.hk,{{rule}}
DOMAIN-SUFFIX,rsshub.app,{{rule}}
DOMAIN-SUFFIX,scmp.com,{{rule}}
DOMAIN-SUFFIX,scribd.com,{{rule}}
DOMAIN-SUFFIX,seatguru.com,{{rule}}
DOMAIN-SUFFIX,shadowsocks.org,{{rule}}
DOMAIN-SUFFIX,shindanmaker.com,{{rule}}
DOMAIN-SUFFIX,shopee.tw,{{rule}}
DOMAIN-SUFFIX,signal.org,{{rule}}
DOMAIN-SUFFIX,sina.com.hk,{{rule}}
DOMAIN-SUFFIX,slideshare.net,{{rule}}
DOMAIN-SUFFIX,softfamous.com,{{rule}}
DOMAIN-SUFFIX,spiegel.de,{{rule}}
DOMAIN-SUFFIX,startpage.com,{{rule}}
DOMAIN-SUFFIX,steamcommunity.com,{{rule}}
DOMAIN-SUFFIX,steemit.com,{{rule}}
DOMAIN-SUFFIX,steemitwallet.com,{{rule}}
DOMAIN-SUFFIX,straitstimes.com,{{rule}}
DOMAIN-SUFFIX,streamable.com,{{rule}}
DOMAIN-SUFFIX,streema.com,{{rule}}
DOMAIN-SUFFIX,substack.com,{{rule}}
DOMAIN-SUFFIX,t66y.com,{{rule}}
DOMAIN-SUFFIX,tapatalk.com,{{rule}}
DOMAIN-SUFFIX,teco-hk.org,{{rule}}
DOMAIN-SUFFIX,teco-mo.org,{{rule}}
DOMAIN-SUFFIX,teddysun.com,{{rule}}
DOMAIN-SUFFIX,textnow.me,{{rule}}
DOMAIN-SUFFIX,theguardian.com,{{rule}}
DOMAIN-SUFFIX,theinitium.com,{{rule}}
DOMAIN-SUFFIX,themoviedb.org,{{rule}}
DOMAIN-SUFFIX,thetvdb.com,{{rule}}
DOMAIN-SUFFIX,time.com,{{rule}}
DOMAIN-SUFFIX,tineye.com,{{rule}}
DOMAIN-SUFFIX,tiny.cc,{{rule}}
DOMAIN-SUFFIX,tinyurl.com,{{rule}}
DOMAIN-SUFFIX,torproject.org,{{rule}}
DOMAIN-SUFFIX,tradingview.com,{{rule}}
DOMAIN-SUFFIX,tumblr.com,{{rule}}
DOMAIN-SUFFIX,turbobit.net,{{rule}}
DOMAIN-SUFFIX,tutanota.com,{{rule}}
DOMAIN-SUFFIX,tvboxnow.com,{{rule}}
DOMAIN-SUFFIX,udn.com,{{rule}}
DOMAIN-SUFFIX,unseen.is,{{rule}}
DOMAIN-SUFFIX,upmedia.mg,{{rule}}
DOMAIN-SUFFIX,uptodown.com,{{rule}}
DOMAIN-SUFFIX,urbandictionary.com,{{rule}}
DOMAIN-SUFFIX,ustream.tv,{{rule}}
DOMAIN-SUFFIX,uwants.com,{{rule}}
DOMAIN-SUFFIX,v2ex.com,{{rule}}
DOMAIN-SUFFIX,v2fly.org,{{rule}}
DOMAIN-SUFFIX,v2ray.com,{{rule}}
DOMAIN-SUFFIX,viber.com,{{rule}}
DOMAIN-SUFFIX,videopress.com,{{rule}}
DOMAIN-SUFFIX,vimeo.com,{{rule}}
DOMAIN-SUFFIX,voachinese.com,{{rule}}
DOMAIN-SUFFIX,voanews.com,{{rule}}
DOMAIN-SUFFIX,voxer.com,{{rule}}
DOMAIN-SUFFIX,vzw.com,{{rule}}
DOMAIN-SUFFIX,w3schools.com,{{rule}}
DOMAIN-SUFFIX,washingtonpost.com,{{rule}}
DOMAIN-SUFFIX,wattpad.com,{{rule}}
DOMAIN-SUFFIX,whoer.net,{{rule}}
DOMAIN-SUFFIX,wikiwand.com,{{rule}}
DOMAIN-SUFFIX,winudf.com,{{rule}}
DOMAIN-SUFFIX,wire.com,{{rule}}
DOMAIN-SUFFIX,wn.com,{{rule}}
DOMAIN-SUFFIX,wordpress.com,{{rule}}
DOMAIN-SUFFIX,worldcat.org,{{rule}}
DOMAIN-SUFFIX,wsj.com,{{rule}}
DOMAIN-SUFFIX,wsj.net,{{rule}}
DOMAIN-SUFFIX,xhamster.com,{{rule}}
DOMAIN-SUFFIX,xn--90wwvt03e.com,{{rule}}
DOMAIN-SUFFIX,xn--i2ru8q2qg.com,{{rule}}
DOMAIN-SUFFIX,xnxx.com,{{rule}}
DOMAIN-SUFFIX,xvideos.com,{{rule}}
DOMAIN-SUFFIX,yadi.sk,{{rule}}
DOMAIN-SUFFIX,yahoo.com,{{rule}}
DOMAIN-SUFFIX,yandex.ru,{{rule}}
DOMAIN-SUFFIX,ycombinator.com,{{rule}}
DOMAIN-SUFFIX,yesasia.com,{{rule}}
DOMAIN-SUFFIX,yes-news.com,{{rule}}
DOMAIN-SUFFIX,yomiuri.co.jp,{{rule}}
DOMAIN-SUFFIX,you-get.org,{{rule}}
DOMAIN-SUFFIX,zaobao.com,{{rule}}
DOMAIN-SUFFIX,zello.com,{{rule}}
DOMAIN-SUFFIX,zeronet.io,{{rule}}
DOMAIN-SUFFIX,z-lib.org,{{rule}}
DOMAIN-SUFFIX,zoom.us,{{rule}}

DOMAIN,cc.tvbs.com.tw,{{rule}}
DOMAIN,clubhouse.pubnubapi.com,{{rule}}
DOMAIN,ocsp.int-x3.letsencrypt.org,{{rule}}
DOMAIN,us.weibo.com,{{rule}}

DOMAIN-SUFFIX,edu,{{rule}}
DOMAIN-SUFFIX,gov,{{rule}}
DOMAIN-SUFFIX,mil,{{rule}}

#(IPBlackhole)
# > Google
DOMAIN-SUFFIX,abc.xyz,{{rule}}
DOMAIN-SUFFIX,advertisercommunity.com,{{rule}}
DOMAIN-SUFFIX,ampproject.org,{{rule}}
DOMAIN-SUFFIX,android.com,{{rule}}
DOMAIN-SUFFIX,androidify.com,{{rule}}
DOMAIN-SUFFIX,autodraw.com,{{rule}}
DOMAIN-SUFFIX,capitalg.com,{{rule}}
DOMAIN-SUFFIX,certificate-transparency.org,{{rule}}
DOMAIN-SUFFIX,chrome.com,{{rule}}
DOMAIN-SUFFIX,chromeexperiments.com,{{rule}}
DOMAIN-SUFFIX,chromestatus.com,{{rule}}
DOMAIN-SUFFIX,chromium.org,{{rule}}
DOMAIN-SUFFIX,creativelab5.com,{{rule}}
DOMAIN-SUFFIX,debug.com,{{rule}}
DOMAIN-SUFFIX,deepmind.com,{{rule}}
DOMAIN-SUFFIX,dialogflow.com,{{rule}}
DOMAIN-SUFFIX,firebaseio.com,{{rule}}
DOMAIN-SUFFIX,getmdl.io,{{rule}}
DOMAIN-SUFFIX,ggpht.com,{{rule}}
DOMAIN-SUFFIX,gmail.com,{{rule}}
DOMAIN-SUFFIX,gmodules.com,{{rule}}
DOMAIN-SUFFIX,godoc.org,{{rule}}
DOMAIN-SUFFIX,gstatic.com,{{rule}}
DOMAIN-SUFFIX,gv.com,{{rule}}
DOMAIN-SUFFIX,gwtproject.org,{{rule}}
DOMAIN-SUFFIX,itasoftware.com,{{rule}}
DOMAIN-SUFFIX,madewithcode.com,{{rule}}
DOMAIN-SUFFIX,material.io,{{rule}}
DOMAIN-SUFFIX,page.link,{{rule}}
DOMAIN-SUFFIX,polymer-project.org,{{rule}}
# DOMAIN-SUFFIX,recaptcha.net,{{rule}}
DOMAIN-SUFFIX,shattered.io,{{rule}}
DOMAIN-SUFFIX,synergyse.com,{{rule}}
DOMAIN-SUFFIX,telephony.goog,{{rule}}
DOMAIN-SUFFIX,tensorflow.org,{{rule}}
DOMAIN-SUFFIX,tfhub.dev,{{rule}}
DOMAIN-SUFFIX,tiltbrush.com,{{rule}}
DOMAIN-SUFFIX,waveprotocol.org,{{rule}}
DOMAIN-SUFFIX,waymo.com,{{rule}}
DOMAIN-SUFFIX,webmproject.org,{{rule}}
DOMAIN-SUFFIX,webrtc.org,{{rule}}
DOMAIN-SUFFIX,whatbrowser.org,{{rule}}
DOMAIN-SUFFIX,widevine.com,{{rule}}
DOMAIN-SUFFIX,x.company,{{rule}}
DOMAIN-SUFFIX,youtu.be,{{rule}}
DOMAIN-SUFFIX,yt.be,{{rule}}
DOMAIN-SUFFIX,ytimg.com,{{rule}}

# > Facebook
DOMAIN-KEYWORD,.facebook.,{{rule}}
DOMAIN-SUFFIX,facebookmail.com,{{rule}}
# > Others
DOMAIN-SUFFIX,noxinfluencer.com,{{rule}}
DOMAIN-SUFFIX,smartmailcloud.com,{{rule}}
DOMAIN-SUFFIX,weebly.com,{{rule}}
DOMAIN-SUFFIX,twitter.jp,{{rule}}

#(Region-RestrictedAccessDenied)
#(Apple)
DOMAIN-SUFFIX,appsto.re,{{rule}}
DOMAIN,books.itunes.apple.com,{{rule}}
DOMAIN-SUFFIX,smoot.apple.com,{{rule}}
DOMAIN,beta.music.apple.com,{{rule}}
DOMAIN,lookup-api.apple.com,{{rule}}
# > WebPreview
DOMAIN,apps.apple.com,{{rule}}
DOMAIN,books.apple.com,{{rule}}
DOMAIN,itunes.apple.com,{{rule}}
DOMAIN,tv.apple.com,{{rule}}
# > Podcasts,{{rule}}
DOMAIN,amp-api.podcasts.apple.com,{{rule}}
DOMAIN,bookkeeper.itunes.apple.com,{{rule}}
# > News
DOMAIN,gateway.icloud.com,{{rule}}
DOMAIN-SUFFIX,apple.news,{{rule}}
DOMAIN,news-assets.apple.com,{{rule}}
DOMAIN,news-client.apple.com,{{rule}}
DOMAIN,news-client-search.apple.com,{{rule}}
DOMAIN,news-edge.apple.com,{{rule}}
DOMAIN,news-events.apple.com,{{rule}}
DOMAIN,apple.comscoreresearch.com,{{rule}}

#Google
DOMAIN-SUFFIX,go.dev,{{rule}}
DOMAIN-SUFFIX,golang.org,{{rule}}
# > Others,{{rule}}
DOMAIN-SUFFIX,aicoin.com,{{rule}}
DOMAIN-SUFFIX,aimoon.com,{{rule}}
DOMAIN-SUFFIX,bing.com,{{rule}}
DOMAIN-SUFFIX,cccat.io,{{rule}}
DOMAIN-SUFFIX,dubox.com,{{rule}}
DOMAIN-SUFFIX,duboxcdn.com,{{rule}}
DOMAIN-SUFFIX,ifixit.com,{{rule}}
DOMAIN-SUFFIX,mangakakalot.com,{{rule}}
DOMAIN-SUFFIX,shopeemobile.com,{{rule}}
DOMAIN-SUFFIX,sushi.com,{{rule}}

#(NetworkJitter)
# > Apple
DOMAIN,appleid.apple.com,{{rule}}
DOMAIN,developer.apple.com,{{rule}}
DOMAIN,www.icloud.com,{{rule}}
DOMAIN,ocsp.apple.com,{{rule}}
# > DigiCert,{{rule}}
DOMAIN,cacerts.digicert.com,{{rule}}
DOMAIN,crl3.digicert.com,{{rule}}
DOMAIN,crl4.digicert.com,{{rule}}
DOMAIN,ocsp.digicert.com,{{rule}}
# > Others
DOMAIN-SUFFIX,cloudcone.com.cn,{{rule}}
DOMAIN-SUFFIX,inkbunny.net,{{rule}}
DOMAIN-SUFFIX,metapix.net,{{rule}}
DOMAIN-SUFFIX,s3.amazonaws.com,{{rule}}
DOMAIN-SUFFIX,zaobao.com.sg,{{rule}}
DOMAIN,international-gfe.download.nvidia.com,{{rule}}
{% endmacro %}